name: Deploy to AWS
on:
  push:
    branches:
      - main-sls
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install Docker (required for Serverless Framework with Docker images)
    - name: Install Docker
      uses: docker/setup-buildx-action@v2

    # Deploy using Serverless Framework
    - name: serverless deploy
      uses: serverless/github-action@v4
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
